USERNAME = "username@gmail.com"
PASSWORD = "password"
IMAP_SERVER = "imap.gmail.com"
AGENCY_ADDRESS = "offers@realagency.com"
AGENCY_URL = "https://www.realagency.com"
REGSTR = "Now Available: (.+, .+)"
SEPARATOR = ","